Revised distributions for stochasticmux
pescadores/pescador pull request #171
Opened 2024-02-01 03:14 UTC by bmcfee

This PR implements several changes described in #148 

- New distributions for stochasticmux: `const` and `binomial` (new default)
- Adjusted the poisson mode so that the expected value is actually `rate` and not `rate+1`

I've also relaxed the uniform convergence unit tests.  A p-value of >=0.95 was probably overkill for the sample size we were drawing, and I've reduced it to 0.5.  Strangely, poisson was giving me the most trouble here, while const and binomial were behaving better.  It's probably an artifact of setting `rate=2` in the test.

2024-02-01 03:31 UTC, bmcfee commented
There's a bit of weirdness here in the initialization with binomial mode.  (Will come back to this later...)

The binomials are parametrized by `Bin((rate-1)/(1-p), 1-p)` where `p` is the probability of selecting the streamer from the active set.  The reason for this dependence is subtle, but it ensures that the replacement times for streamers don't concentrate too much; a streamer gets replaced on average every `rate * N_active` samples, with variance like `rate * N_active * (N_active-1)`.  (At least, assuming uniform weights on the streamers.)

The weirdness arises when we initialize streamers on at a time: the weight distribution is not fully known until the first batch of active streamers are fully initialized, so the calculations for `p` above are generally going to be wrong.  In the extreme case, the first active streamer will use the poisson approximation (since `p=1` when there are no other streamers active yet); the second streamer will have `bin((rate-1)/0.5, 0.5)` (assuming uniform weights again), the third will have `bin((rate-1)/0.666, 0.666)`, and so on.  In all cases, the expected values will be the same, but the first few streamers will have higher rate variance than the later ones.  Specifically, the variance sequence will look like (again, assuming uniform streamer weights) of `(rate-1)/n` (for `n=1,2, ..., n_active`).

Now, we could hack around this by pre-determining the weights so that everything is primed properly.  However, I think it might actually be beneficial to leave it as is because it injects more randomness in the rate distributions early on, which ought to have a comparable effect to having random offsets in a burn-in phase as @ejhumphrey suggested in #132 .

It's a bit weird, but given the potentially dynamic nature of the active stream distribution (especially in exhaustive mode), it won't be possible to always ensure that the rate distribution for a streamer is "correct" over time.  The best we can do is sample the rate value according to whatever the distribution will be at the time the streamer is activated.

2024-02-01 14:58 UTC, bmcfee commented
Having slept on it, i think a better solution here is to initialize the active set weights by a random draw from the weights array instead of with zeros. This won't have any effect on const or poisson, but it will put the binomial mode in a less quirky position at initialization time.

2024-03-08 16:00 UTC, bmcfee commented
@cjacoby :wave: I know it's been a gajillion years, but do you have any interest in looking this over?  I think it's basically good to go, but it does have some kinda breaky behavior relative to older versions that I'd like to get another set of eyes on.

Quick TLDR is summarized in https://github.com/pescadores/pescador/issues/148#issuecomment-1919834323

2024-03-08 21:57 UTC, cjacoby requested changes
lgtm other than I think a small comment improvement would improve it (for me in 6mo to a year when I come back and can't remember what this is about).

2024-03-08 21:57 UTC, cjacoby commented on pescador/mux.py
> +            In each case, the expected number of samples will be `rate`.
I think for best user experience, it would be nice to have a quick summary of (as a consumer of the library) when you might want to use each of these distributions.

Or, perhaps a tl;dr, with a link back to the analysis in the issue for in depth understanding.

2024-03-09 12:28 UTC, bmcfee commented on pescador/mux.py
> +            In each case, the expected number of samples will be `rate`.
That's a good point. I think what I'll do is write up a section for the docs that goes over this in detail. Will try to get that done some time in the next week.

2024-03-11 19:47 UTC, bmcfee commented
Ok, doc section is added and back-link is included.  I tried to clean it up a bit from my original notebook (4 years ago!) and put in some expository text.  Hopefully it makes sense?

2024-03-11 23:45 UTC, cjacoby approved these changes

2024-03-11 23:46 UTC, merged